"""Two/three-column ASCII — the format everything can be exported to.

No spec: the shape *is* the format.  Rows of ``x y [σ]``, comment lines
starting ``#``/``!``/``'``/``/``, whitespace or comma separated.  Because there
is nothing to recognise, this reader is the last entry in the dispatch order and
claims whatever is left — which is **not** the same as everything: a file whose
first 4 kB holds a NUL is binary and is not claimed, so it reaches
``identify_format``'s refusal by name rather than this reader's decoder.

**The x column is 2θ unless the file says otherwise, and only a declaration
counts as saying.**  Mantid writes powder data to this format for both
constant-wavelength and time-of-flight instruments — a POWGEN bank and a lab
scan are the same three columns — and states which in a comment header:

    ``' File generated by Mantid:``
    ``' Instrument: POWGEN``
    ``' The X-axis unit is: Time-of-flight``

That third line is what this reader reads.  It is a **stated unit**, which is
the only shape that can be trusted: the word "tof" also turns up in file names,
provenance comments and workspace names (``# from gem77976_b1_tof.dat``), and
flipping a pattern's abscissa on a substring in a comment would change what
every number in the file *means* on the strength of a coincidence.  A file that
carries a TOF-looking token without stating a unit is therefore read as 2θ —
and **says so** (``PATTERN_X_AXIS_ASSUMED``), which is the third row of the axis
policy (``io/CLAUDE.md`` § The axis is never trusted) rather than a silence.
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

import numpy as np

from ...schemas.common import Diagnostic
from ...schemas.pattern import AxisKind, PatternData
from .base import (
    PatternFormat,
    ascending,
    check_axis,
    head,
    looks_binary,
    pattern_data,
)

#: A comment line that **states the x-axis unit**.  Mantid's own spelling is
#: ``The X-axis unit is: Time-of-flight``; the looser ``X unit = …`` costs
#: nothing and is what a hand-edited export tends to keep.  The word ``axis`` or
#: ``unit`` is *required* and the ``x`` must start a word, which is what keeps
#: this from matching a comment that merely ends in a colon — ``# Max: 90``
#: otherwise reads as a stated x-axis unit of "90" and earns the file a
#: spurious ``PATTERN_X_AXIS_ASSUMED``.  The comment marker is already stripped
#: by the caller.
_UNIT_RE = re.compile(
    r"\bx[-\s]?(?:axis\s*(?:units?)?|units?)\s*(?:is)?\s*[:=]\s*(\S.*?)\s*$",
    re.I)

#: What a stated unit has to contain to *be* a flight time.  ``tof`` is matched
#: as a whole word only: it is a substring of nothing here, but it is a
#: substring of plenty elsewhere and the boundary is what keeps this a
#: declaration rather than a search.
_TOF_UNIT_RE = re.compile(
    r"time[-\s]?of[-\s]?flight|\btof\b|microsecond|\bus\b|\bµs\b|\busec\b", re.I)

#: …and to be an angle.  ``d`` and ``q`` are deliberately absent: a d-spacing or
#: a Q column is neither of this package's two axes, so it falls to
#: :func:`check_axis`'s refusal arm rather than being classified here.
_ANGLE_UNIT_RE = re.compile(
    r"2\s*theta|two[-\s]?theta|2θ|\bdegree|\bdeg\b|\bangle\b", re.I)

#: Units that are **recognisably something else** — the policy's refusal arm.
#: These are Mantid's own Unit Factory names, because Mantid is what writes this
#: header, and a bank exported in any of them parses perfectly and refines to a
#: cell that is wrong by a geometry rather than by a tolerance.  Matched on the
#: stated unit only, never on the file's numbers.
_OTHER_UNITS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"d[-\s]?spacing", re.I), "a d-spacing in Å"),
    (re.compile(r"momentum\s*transfer|^q$|\bq\s*\(", re.I),
     "a momentum transfer Q in Å⁻¹"),
    (re.compile(r"q\s*squared", re.I), "a Q² in Å⁻²"),
    (re.compile(r"wavelength", re.I), "a wavelength in Å"),
    (re.compile(r"\benergy\b|\bdeltae\b|wavenumber", re.I),
     "a neutron energy"),
    (re.compile(r"\bmomentum\b", re.I), "a neutron momentum in Å⁻¹"),
)

#: A TOF-looking token anywhere in a comment, used **only** to decide whether
#: an assumed 2θ axis is worth a diagnostic.  Never to set the axis.
_TOF_HINT_RE = re.compile(r"time[-\s]?of[-\s]?flight|\btof\b", re.I)

_COMMENT_MARKERS = ("#", "!", "'", "/")


def _stated_axis(comments: list[str]
                 ) -> tuple[AxisKind | None, str | None, str | None]:
    """``(axis, stated, other)`` from the comment block — the file's declaration.

    The three-way policy's own three answers.  ``axis`` is the quantity when the
    file states one this reader can hold; ``other`` is what the axis *is* when
    it states one it cannot (a d-spacing, a Q), for :func:`check_axis`'s
    refusal; both ``None`` is "states nothing recognisable", which is the
    ordinary case for a format with no spec and is not an error.  ``stated`` is
    the unit verbatim in every case, for the metadata and for a message that has
    to quote it.
    """
    for line in comments:
        m = _UNIT_RE.search(line)
        if not m:
            continue
        stated = m.group(1)
        if _TOF_UNIT_RE.search(stated):
            return "tof", stated, None
        if _ANGLE_UNIT_RE.search(stated):
            return "two_theta", stated, None
        for pattern, what in _OTHER_UNITS:
            if pattern.search(stated):
                return None, stated, what
        return None, stated, None
    return None, None, None


def read_xy(path: str | Path, *,
            diagnostics: list[Diagnostic] | None = None) -> PatternData:
    """Rows of ``x y [σ]``, read by position; x is 2θ unless the file states a flight time.

    **A row is data only if it has the file's usual column count** (issue
    #266).  A header line that starts with a digit parses on its first three
    tokens: PDFgetX2's detector table put a point at (0, 1) on every file one
    reporter had.  So each row keeps its token count, the most common count
    is the file's, and a row with any other is dropped and reported as
    ``PATTERN_ROWS_DROPPED``.  A tie goes to the count of the last row,
    because a header sits above its data.  A header row with the data's own
    count is out of this check's reach; the axis check in ``read_pattern``
    still sees one landing at or below 0°.
    """
    p = Path(path)
    rows: list[tuple[int, list[str], list[float]]] = []
    comments: list[str] = []
    # the mark decides the codec, so a UTF-16 export from Windows vendor
    # software reads instead of dying on "no numeric data found"
    text = p.read_text(encoding=head(p).encoding, errors="replace")
    for n, line in enumerate(text.splitlines(), 1):
        s = line.strip()
        if not s:
            continue
        if s.startswith(_COMMENT_MARKERS):
            comments.append(s.lstrip("".join(_COMMENT_MARKERS)).strip())
            continue
        parts = s.replace(",", " ").split()
        try:
            vals = [float(v) for v in parts[:3]]
        except ValueError:
            continue
        if len(vals) >= 2:
            rows.append((n, parts, vals))
    if not rows:
        raise ValueError(f"no numeric data found in {p}")
    counts = Counter(len(parts) for _, parts, _ in rows)
    arity = max(counts, key=lambda k: (counts[k], k == len(rows[-1][1])))
    dropped = [(n, parts) for n, parts, _ in rows if len(parts) != arity]
    if dropped and diagnostics is not None:
        shown = "; ".join(f"line {n}: {' '.join(parts)!r}"
                          for n, parts in dropped[:3])
        more = f", and {len(dropped) - 3} more" if len(dropped) > 3 else ""
        diagnostics.append(Diagnostic(
            level="warning", code="PATTERN_ROWS_DROPPED",
            message=(
                f"{p.name}: {len(dropped)} numeric row(s) have a column count "
                f"other than the file's {arity}, and were not read as data "
                f"({shown}{more})."),
            where=[f"line {n}" for n, _ in dropped],
            suggestion=(
                "A header table or a limits row reads this way. If a dropped "
                "row is a measured point, the file mixes column counts: "
                "re-export it with one count on every row."),
            value=float(len(dropped)),
        ))
    # one column count, so every kept row parsed the same number of values
    arr = np.array([vals for _, parts, vals in rows if len(parts) == arity],
                   dtype=np.float64)
    n_cols = arr.shape[1]
    sigma = arr[:, 2] if n_cols >= 3 and np.any(arr[:, 2] > 0) else None

    axis, stated, other = _stated_axis(comments)
    if axis is None:
        # No recognised declaration: the axis is *assumed*, which is the third
        # row of the policy and the one that has to speak.  ``note`` carries the
        # TOF hint when there is one — a file that mentions a flight time
        # somewhere and states no unit is exactly the file whose reader should
        # not be silent, and exactly the file whose reader must not guess.
        hint = next((c for c in comments if _TOF_HINT_RE.search(c)), None)
        note = ("" if hint is None else
                f" This file's comments mention a flight time "
                f"({hint!r}) but state no x-axis unit, and a mention is not a "
                f"declaration — export it with Mantid's header line "
                f"(\"The X-axis unit is: Time-of-flight\") to read it as TOF.")
        check_axis(stated or "", path=p, field="x-axis unit",
                   two_theta=False, other=other, note=note,
                   remedy=("Export the bank in time-of-flight or in 2θ: those "
                           "are the two abscissae PatternData holds."),
                   diagnostics=diagnostics if (stated or hint) else None)
        axis = "two_theta"
    x, y, sig = ascending(arr[:, 0], arr[:, 1], sigma, path=p, fmt=XY,
                          axis=axis, diagnostics=diagnostics)
    return pattern_data(p, x, y, sig, axis=axis, source_file=p.name, format="xy",
                        x_label=stated)


XY = PatternFormat(
    name="xy",
    title="Two/three-column ASCII (.xy / .xye)",
    extensions=(".xy", ".xye", ".dat", ".prn", ".txt"),
    sniff="any text file left over that parses as numeric rows",
    sigma="the third column when present and positive, else the Poisson fallback",
    # last, but no longer *total*: a file with a NUL in its first 4 kB is not
    # claimed, so a binary vendor pattern reaches identify_format's refusal —
    # which names the formats this build reads — instead of reaching
    # ``read_text`` and dying as a bare UnicodeDecodeError.  "Does this format
    # claim the file" already lives in ``matches``; a separate guard would be a
    # second place that knows about binary files.
    matches=lambda p: not looks_binary(head(p)),
    read=read_xy,
)
