"""Two/three-column ASCII — the format everything can be exported to.

No spec: the shape *is* the format.  Rows of ``x y [σ]``, comment lines
starting ``#``/``!``/``'``/``/``, whitespace or comma separated.  Because there
is nothing to recognise, this reader is the last entry in the dispatch order and
claims whatever is left — which is **not** the same as everything: a file whose
first 4 kB holds a NUL is binary and is not claimed, so it reaches
``identify_format``'s refusal by name rather than this reader's decoder.

**The x column is 2θ unless the file says otherwise, and only a declaration
counts as saying.**  Mantid writes powder data to this format for both
constant-wavelength and time-of-flight instruments — a POWGEN bank and a lab
scan are the same three columns — and states which in a comment header:

    ``' File generated by Mantid:``
    ``' Instrument: POWGEN``
    ``' The X-axis unit is: Time-of-flight``

That third line is what this reader reads.  It is a **stated unit**, which is
the only shape that can be trusted: the word "tof" also turns up in file names,
provenance comments and workspace names (``# from gem77976_b1_tof.dat``), and
flipping a pattern's abscissa on a substring in a comment would change what
every number in the file *means* on the strength of a coincidence.  A file that
carries a TOF-looking token without stating a unit is therefore read as 2θ —
and **says so** (``PATTERN_X_AXIS_ASSUMED``), which is the third row of the axis
policy (``io/CLAUDE.md`` § The axis is never trusted) rather than a silence.

**The same header states the *y* unit, and that one settles the intensity
basis** — whether a channel holds the counts it recorded or those counts
already divided by the channel's own width (``PatternData.intensity_basis``,
GSAS's I_o = I'_o/(W·I_i)).  Read by :func:`_stated_basis`, and read the same
way: only a declaration counts, and only a unit stating a division by a unit
of *flight time* is a density.  The POWGEN export above states ``Counts per
microAmp.hour``, which is a count normalised by an integrated proton charge —
a scalar, degenerate with the phase scale — so a Mantid header is by itself no
evidence of a density.  A file stating nothing leaves the field ``None``.
"""

from __future__ import annotations

import re
from pathlib import Path

import numpy as np

from ...schemas.common import Diagnostic
from ...schemas.pattern import AxisKind, IntensityBasis, PatternData
from .base import (
    PatternFormat,
    ascending,
    check_axis,
    head,
    looks_binary,
    pattern_data,
)

#: A comment line that **states the x-axis unit**.  Mantid's own spelling is
#: ``The X-axis unit is: Time-of-flight``; the looser ``X unit = …`` costs
#: nothing and is what a hand-edited export tends to keep.  The word ``axis`` or
#: ``unit`` is *required* and the ``x`` must start a word, which is what keeps
#: this from matching a comment that merely ends in a colon — ``# Max: 90``
#: otherwise reads as a stated x-axis unit of "90" and earns the file a
#: spurious ``PATTERN_X_AXIS_ASSUMED``.  The comment marker is already stripped
#: by the caller.
_UNIT_RE = re.compile(
    r"\bx[-\s]?(?:axis\s*(?:units?)?|units?)\s*(?:is)?\s*[:=]\s*(\S.*?)\s*$",
    re.I)

#: What a stated unit has to contain to *be* a flight time.  ``tof`` is matched
#: as a whole word only: it is a substring of nothing here, but it is a
#: substring of plenty elsewhere and the boundary is what keeps this a
#: declaration rather than a search.
_TOF_UNIT_RE = re.compile(
    r"time[-\s]?of[-\s]?flight|\btof\b|microsecond|\bus\b|\bµs\b|\busec\b", re.I)

#: …and to be an angle.  ``d`` and ``q`` are deliberately absent: a d-spacing or
#: a Q column is neither of this package's two axes, so it falls to
#: :func:`check_axis`'s refusal arm rather than being classified here.
_ANGLE_UNIT_RE = re.compile(
    r"2\s*theta|two[-\s]?theta|2θ|\bdegree|\bdeg\b|\bangle\b", re.I)

#: Units that are **recognisably something else** — the policy's refusal arm.
#: These are Mantid's own Unit Factory names, because Mantid is what writes this
#: header, and a bank exported in any of them parses perfectly and refines to a
#: cell that is wrong by a geometry rather than by a tolerance.  Matched on the
#: stated unit only, never on the file's numbers.
_OTHER_UNITS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"d[-\s]?spacing", re.I), "a d-spacing in Å"),
    (re.compile(r"momentum\s*transfer|^q$|\bq\s*\(", re.I),
     "a momentum transfer Q in Å⁻¹"),
    (re.compile(r"q\s*squared", re.I), "a Q² in Å⁻²"),
    (re.compile(r"wavelength", re.I), "a wavelength in Å"),
    (re.compile(r"\benergy\b|\bdeltae\b|wavenumber", re.I),
     "a neutron energy"),
    (re.compile(r"\bmomentum\b", re.I), "a neutron momentum in Å⁻¹"),
)

#: A TOF-looking token anywhere in a comment, used **only** to decide whether
#: an assumed 2θ axis is worth a diagnostic.  Never to set the axis.
_TOF_HINT_RE = re.compile(r"time[-\s]?of[-\s]?flight|\btof\b", re.I)

#: The **y**-axis twin of :data:`_UNIT_RE`.  Mantid writes it in the same block
#: and the same shape (``' The Y-axis unit is: Counts per microAmp.hour``), so
#: it is read the same way — and, like the x one, only as a *declaration*.
_Y_UNIT_RE = re.compile(
    r"\by[-\s]?(?:axis\s*(?:units?)?|units?)\s*(?:is)?\s*[:=]\s*(\S.*?)\s*$",
    re.I)

#: A stated y unit that is a count **per unit flight time**: the file has
#: already divided by the channel width and the flight-time forward model owes
#: it no factor of W (``schemas.pattern.PatternData.intensity_basis``).  The
#: time unit is required — this is the whole discrimination, and it is why
#: "Counts per microAmp.hour" and "Counts per second" are *not* here.  Both of
#: those divide by a **scalar** (an integrated proton charge, a counting time),
#: which is exactly degenerate with the phase scale; only a division by the
#: channel's own width has a shape in flight time.
_DENSITY_UNIT_RE = re.compile(
    r"per\s*(?:micro\s*second|microsec|µs|us\b|usec)"
    r"|/\s*(?:µs|us\b|microsecond)"
    r"|counts?\s*[/·]\s*(?:µs|us\b)", re.I)

#: …and one that is a count per channel, however else it is normalised.  Read
#: after :data:`_DENSITY_UNIT_RE`, so "Counts per microsecond" is a density and
#: "Counts per microAmp.hour" is a count.
_COUNTS_UNIT_RE = re.compile(r"\bcounts?\b", re.I)


def _stated_basis(comments: list[str]) -> IntensityBasis | None:
    """The intensity basis from a **stated** y-axis unit, or ``None``.

    ``io/CLAUDE.md`` § The intensity basis is never inferred, one rank down
    from § The axis is never trusted and for the identical reason: a count per
    channel and a count per microsecond are both plausible positive reals, and
    on the one real pair obtainable they differ by a factor of 4.4 that a
    refinement would charge to a displacement parameter.  So the y column's
    meaning is settled by what the file *says* about it and by nothing else,
    and an unstated one stays ``None`` rather than defaulting to either.

    The one obtainable Mantid ``.xye`` — an SNS POWGEN bank — states ``Counts
    per microAmp.hour``, i.e. a **count**, normalised by an integrated proton
    charge.  That is the case worth naming: the presence of a Mantid header is
    *not* evidence of a density, and reading it as one would have applied the
    wrong branch to that file.
    """
    for line in comments:
        m = _Y_UNIT_RE.search(line)
        if not m:
            continue
        stated = m.group(1)
        if _DENSITY_UNIT_RE.search(stated):
            return "density"
        if _COUNTS_UNIT_RE.search(stated):
            return "counts"
        return None
    return None

_COMMENT_MARKERS = ("#", "!", "'", "/")


def _stated_axis(comments: list[str]
                 ) -> tuple[AxisKind | None, str | None, str | None]:
    """``(axis, stated, other)`` from the comment block — the file's declaration.

    The three-way policy's own three answers.  ``axis`` is the quantity when the
    file states one this reader can hold; ``other`` is what the axis *is* when
    it states one it cannot (a d-spacing, a Q), for :func:`check_axis`'s
    refusal; both ``None`` is "states nothing recognisable", which is the
    ordinary case for a format with no spec and is not an error.  ``stated`` is
    the unit verbatim in every case, for the metadata and for a message that has
    to quote it.
    """
    for line in comments:
        m = _UNIT_RE.search(line)
        if not m:
            continue
        stated = m.group(1)
        if _TOF_UNIT_RE.search(stated):
            return "tof", stated, None
        if _ANGLE_UNIT_RE.search(stated):
            return "two_theta", stated, None
        for pattern, what in _OTHER_UNITS:
            if pattern.search(stated):
                return None, stated, what
        return None, stated, None
    return None, None, None


def read_xy(path: str | Path, *,
            diagnostics: list[Diagnostic] | None = None) -> PatternData:
    p = Path(path)
    rows = []
    comments: list[str] = []
    # the mark decides the codec, so a UTF-16 export from Windows vendor
    # software reads instead of dying on "no numeric data found"
    for line in p.read_text(encoding=head(p).encoding, errors="replace").splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith(_COMMENT_MARKERS):
            comments.append(s.lstrip("".join(_COMMENT_MARKERS)).strip())
            continue
        parts = s.replace(",", " ").split()
        try:
            vals = [float(v) for v in parts[:3]]
        except ValueError:
            continue
        if len(vals) >= 2:
            rows.append(vals)
    if not rows:
        raise ValueError(f"no numeric data found in {p}")
    n_cols = min(len(r) for r in rows)
    arr = np.array([r[:n_cols] for r in rows], dtype=np.float64)
    sigma = arr[:, 2] if n_cols >= 3 and np.any(arr[:, 2] > 0) else None

    axis, stated, other = _stated_axis(comments)
    if axis is None:
        # No recognised declaration: the axis is *assumed*, which is the third
        # row of the policy and the one that has to speak.  ``note`` carries the
        # TOF hint when there is one — a file that mentions a flight time
        # somewhere and states no unit is exactly the file whose reader should
        # not be silent, and exactly the file whose reader must not guess.
        hint = next((c for c in comments if _TOF_HINT_RE.search(c)), None)
        note = ("" if hint is None else
                f" This file's comments mention a flight time "
                f"({hint!r}) but state no x-axis unit, and a mention is not a "
                f"declaration — export it with Mantid's header line "
                f"(\"The X-axis unit is: Time-of-flight\") to read it as TOF.")
        check_axis(stated or "", path=p, field="x-axis unit",
                   two_theta=False, other=other, note=note,
                   remedy=("Export the bank in time-of-flight or in 2θ: those "
                           "are the two abscissae PatternData holds."),
                   diagnostics=diagnostics if (stated or hint) else None)
        axis = "two_theta"
    x, y, sig = ascending(arr[:, 0], arr[:, 1], sigma, path=p, fmt=XY,
                          axis=axis, diagnostics=diagnostics)
    return pattern_data(p, x, y, sig, axis=axis, source_file=p.name, format="xy",
                        intensity_basis=_stated_basis(comments),
                        x_label=stated)


XY = PatternFormat(
    name="xy",
    title="Two/three-column ASCII (.xy / .xye)",
    extensions=(".xy", ".xye", ".dat", ".prn", ".txt"),
    sniff="any text file left over that parses as numeric rows",
    sigma="the third column when present and positive, else the Poisson fallback",
    # last, but no longer *total*: a file with a NUL in its first 4 kB is not
    # claimed, so a binary vendor pattern reaches identify_format's refusal —
    # which names the formats this build reads — instead of reaching
    # ``read_text`` and dying as a bare UnicodeDecodeError.  "Does this format
    # claim the file" already lives in ``matches``; a separate guard would be a
    # second place that knows about binary files.
    matches=lambda p: not looks_binary(head(p)),
    read=read_xy,
)
