"""The intensity basis: counts per channel, or counts per microsecond.

The other half of GSAS's ``I_o = I'_o/(W·I_i)`` (Larson & Von Dreele, 2004,
LAUR 86-748, Technical Manual p. 127), whose ``I_i`` half is T-3's.  A
calculated Bragg sum is a *density*, so a histogram whose channels hold the
counts they recorded owes it a factor of the channel width W and one already
divided by W does not — and which of the two a file holds is a **declaration**,
never an inference.

**Every fixture here is synthetic and written in this file.**  The real
measurements — the ISIS GEM ``.gss`` against its own ``.xye`` twin, and the
internal banks beside it — are in the rung's report and stay there.
"""

from __future__ import annotations

import numpy as np
import pytest

import rietx as rx
from rietx.model.forward import compile_model
from rietx.model.forward_tof import compile_tof_model
from rietx.params.vector import ParameterTable
from rietx.schemas.pattern import PatternData
from rietx.schemas.structure import Atom, Cell, Phase, Structure

P = rx.Parameter

TOF_LO, TOF_HI = 8000.0, 45000.0
#: Δt/t of the synthetic log-stepped bank below.  Chosen so that W runs a
#: factor of 5.6 across the window — the same order as a real bank's, an ISIS
#: GEM ``RALF`` bank being Δt/t = 0.004 throughout — because a
#: control on a constant-width grid would be measuring a *scale*, which the
#: phase scale absorbs, rather than a slope in flight time, which it does not.
LOG_STEP = 2.0e-3
PROFILE = dict(alpha1=0.45, beta0=0.055, beta1=0.003, sig1=300.0)


# ---------------------------------------------------------------- the fixtures
def silicon(biso: float = 0.5) -> Structure:
    cell = Cell(a=P(value=5.4311946), b=P(value=5.4311946), c=P(value=5.4311946),
                alpha=P(value=90.0), beta=P(value=90.0), gamma=P(value=90.0))
    return Structure(phases=[Phase(
        name="Si", space_group="F d -3 m :2", cell=cell, scale=P(value=1.0),
        atoms=[Atom(label="Si", species="Si", x=P(value=0.125),
                    y=P(value=0.125), z=P(value=0.125), biso=P(value=biso))])])


def bank(two_theta: float = 90.0):
    return rx.Instrument.tof_neutron_bank(
        difc=12000.0, tzero=-5.0, two_theta_bank_deg=two_theta,
        profile=rx.ProfileTOF(**{k: P(value=v) for k, v in PROFILE.items()}))


def log_edges() -> np.ndarray:
    """Bin **edges** of a Δt/t = LOG_STEP histogram over the fitted window.

    Written as edges and not as centres because that is what a histogram is:
    the channel width this whole rung is about is ``e[i+1] - e[i]``, and a
    fixture that started from centres could not state the true answer the
    midpoint convention is checked against.
    """
    n = int(np.log(TOF_HI / TOF_LO) / np.log1p(LOG_STEP)) + 1
    return TOF_LO * (1.0 + LOG_STEP) ** np.arange(n + 1)


def log_grid() -> tuple[np.ndarray, np.ndarray]:
    """``(centres, true widths)`` of that histogram."""
    e = log_edges()
    return 0.5 * (e[:-1] + e[1:]), np.diff(e)


def blank(basis=None) -> PatternData:
    x, _ = log_grid()
    return PatternData(tof=x.tolist(), intensity=[1.0] * len(x),
                       intensity_basis=basis)


def values_of(structure, instrument) -> dict[str, float]:
    return {e.path: e.value for e in ParameterTable(structure, instrument).entries}


# --------------------------------------------------------------- the schema
def test_the_basis_is_a_closed_vocabulary_and_defaults_to_unstated():
    pat = blank()
    assert pat.intensity_basis is None
    assert blank("counts").intensity_basis == "counts"
    assert blank("density").intensity_basis == "density"
    with pytest.raises(Exception):
        blank("cps")


def test_the_basis_round_trips_through_json_and_survives_a_crop():
    pat = blank("counts")
    assert PatternData.model_validate(pat.model_dump(mode="json")) == pat
    # dropping channels does not change what a kept channel holds
    assert pat.crop(10000.0, 20000.0).intensity_basis == "counts"
    assert blank().crop(10000.0, 20000.0).intensity_basis is None


# ------------------------------------------------------- what a reader may say
def _gsas(tmp_path, name, bank_record, header=(), n=60, tof=True):
    p = tmp_path / name
    if "FXYE" in bank_record:
        rows = [f"{1000.0 * (1.002 ** i) + 0.0:15.5f}{10.0:15.5f}{1.0:10.5f}"
                for i in range(n)]
    else:  # ESD: ten 8-character fields to an 80-column record
        # ten 8-character fields to an 80-column record; the pair is a count
        # and its own Poisson esd, invented here
        rows = ["".join(f"{v:8.1f}" for v in (400.0, 20.0) * 5)
                for _ in range(n // 5)]
    p.write_text("a title line\n" + "".join(f"{h}\n" for h in header)
                 + bank_record + "\n" + "\n".join(rows) + "\n",
                 encoding="utf-8")
    return p


MANTID = ("# File generated by Mantid:", "# Instrument: GEM",
          "# with Y multiplied by the bin widths.")


def test_a_mantid_savegss_header_declares_counts(tmp_path):
    """The line Mantid writes when, and only when, ``MultiplyByBinWidth`` was
    on — which is its **default**, and the reason a Mantid ``.gss`` cannot be
    read as a density."""
    p = _gsas(tmp_path, "gem.gss",
              "BANK 1 60 60 RALF    35328      141    35328 0.00400 FXYE",
              header=MANTID)
    diags: list = []
    pat = rx.read_pattern(str(p), diagnostics=diags)
    assert pat.axis == "tof" and pat.intensity_basis == "counts"
    assert "PATTERN_INTENSITY_BASIS_UNKNOWN" not in [d.code for d in diags]


def test_a_bare_ralf_fxye_bank_states_nothing_and_says_so(tmp_path):
    """The same bank without the header: the two answers differ by W(T) and
    nothing in the file chooses, so the reader chooses neither."""
    p = _gsas(tmp_path, "bare.gss",
              "BANK 1 60 60 RALF    35328      141    35328 0.00400 FXYE")
    diags: list = []
    pat = rx.read_pattern(str(p), diagnostics=diags)
    assert pat.axis == "tof" and pat.intensity_basis is None
    said = next(d for d in diags if d.code == "PATTERN_INTENSITY_BASIS_UNKNOWN")
    assert said.level == "warning" and said.where == ["intensity_basis"]
    # a diagnostic a user can act on names the field and both values
    assert "intensity_basis" in said.suggestion
    assert "'counts'" in said.message and "'density'" in said.message


def _time_map(tmp_path, name, nchan=50, first=20000, step=10, flag="ESD"):
    """A ``TIME_MAP`` bank, written the way a real one is: the map first,
    triples of (first channel, flight time, step) in 100 ns clock ticks, then
    the terminating flight time at the last channel."""
    table = "".join(f"{v:8d}" for v in
                    (1, first, step, first + (nchan - 1) * step))
    if flag == "ESD":
        rows = ["".join(f"{float(10 + j):8.1f}{float(1 + j):8.1f}"
                        for j in range(i, min(i + 5, nchan)))
                for i in range(0, nchan, 5)]
    else:
        rows = ["".join(f"{float(10 + j):8.1f}" for j in range(nchan))]
    p = tmp_path / name
    p.write_text("a synthetic TIME_MAP bank\n"
                 f"TIME_MAP    1    4    1 TIME_MAP  100\n{table}\n"
                 f"BANK   1  {nchan} {len(rows)} TIME_MAP  1 {flag}\n"
                 + "\n".join(rows) + "\n", encoding="utf-8")
    return p


@pytest.mark.parametrize("flag", ["ESD", "STD"])
def test_an_esd_layout_and_a_time_map_bintype_are_raw_histograms(tmp_path, flag):
    """Two independent declarations of the same thing, and either alone would
    be enough: an ``STD``/``ESD`` record cannot express a density (``STD`` is
    a repeat count and a six-character integer), and a ``TIME_MAP`` bank is a
    tabulated acquisition-clock map — a form Mantid does not write."""
    pat = rx.read_pattern(str(_time_map(tmp_path, f"acq_{flag}.gsa", flag=flag)))
    assert pat.axis == "tof" and pat.intensity_basis == "counts"


def test_a_constant_wavelength_bank_is_read_the_same_way_and_stays_quiet(
        tmp_path):
    """The field is set on the constant-wavelength arm too — an 11-BM ``ESD``
    bank really does hold counts — but the *diagnostic* is time-of-flight only.
    A 2θ step is constant and folds into the phase scale, so a warning there
    would be one nobody can act on and nobody needs to."""
    p = _gsas(tmp_path, "cw.gsa", "BANK 1 50 10 CONS 1000.0 2.0 ESD")
    diags: list = []
    pat = rx.read_pattern(str(p), diagnostics=diags)
    assert pat.axis == "two_theta" and pat.intensity_basis == "counts"
    assert "PATTERN_INTENSITY_BASIS_UNKNOWN" not in [d.code for d in diags]

    bare = _gsas(tmp_path, "cwbare.xye", "BANK 1 60 60 CONS 1000.0 2.0 FXYE")
    diags = []
    pat = rx.read_pattern(str(bare), diagnostics=diags)
    assert pat.axis == "two_theta" and pat.intensity_basis is None
    assert "PATTERN_INTENSITY_BASIS_UNKNOWN" not in [d.code for d in diags]


def _xye(tmp_path, name, comments):
    p = tmp_path / name
    rows = "\n".join(f"{7000.0 + 3.0 * i:15.5f}{1.0 + i:15.5f}{0.5:10.5f}"
                     for i in range(40))
    p.write_text("".join(f"{c}\n" for c in comments) + rows + "\n",
                 encoding="utf-8")
    return p


HEAD = ("' File generated by Mantid:", "' Instrument: POWGEN",
        "' The X-axis unit is: Time-of-flight")


def test_a_mantid_xye_y_unit_decides_and_a_mantid_header_alone_does_not(
        tmp_path):
    """The row a session would get wrong.

    The one obtainable Mantid ``.xye`` is an SNS POWGEN bank stating ``Counts
    per microAmp.hour`` — a count divided by an integrated proton **charge**,
    which is a scalar and exactly degenerate with the phase scale.  Reading a
    Mantid header as evidence of a density would apply the wrong branch to
    that file, so only a unit naming a division by a unit of flight time is a
    density.
    """
    counts = rx.read_pattern(str(_xye(
        tmp_path, "pg3.xye",
        HEAD + ("' The Y-axis unit is: Counts per microAmp.hour",))))
    assert counts.axis == "tof" and counts.intensity_basis == "counts"

    density = rx.read_pattern(str(_xye(
        tmp_path, "dist.xye",
        HEAD + ("' The Y-axis unit is: Counts per microsecond",))))
    assert density.intensity_basis == "density"

    # states an x unit and no y unit: undetermined, not "density by default"
    silent = rx.read_pattern(str(_xye(tmp_path, "quiet.xye", HEAD)))
    assert silent.axis == "tof" and silent.intensity_basis is None


# ------------------------------------------------------- the width itself
def test_the_channel_width_is_measured_from_the_patterns_own_abscissa():
    """Edges at the midpoints of the neighbours, which is the convention that
    makes adjacent channels' edges agree — and, in the interior, exactly
    ``numpy.gradient``.  Checked against a histogram whose true widths are
    known because the fixture is built from its edges."""
    x, true_w = log_grid()
    model = compile_tof_model(silicon(), bank(), blank("counts"))
    got = model.channel_width_factor()
    assert got is not None and got.shape == x.shape
    # the interior is right to a part in 10^6; the two ends are the one place a
    # midpoint rule cannot see the histogram's own boundary, and they are
    # excluded here as they are excluded from any fitted window
    assert got[1:-1] == pytest.approx(true_w[1:-1], rel=2e-6)


def test_no_width_factor_is_built_where_none_is_owed():
    """``None`` and not an array of ones — the same choice
    ``incident_spectrum`` makes, and for the same reason: a bank owing no
    factor multiplies by *nothing*, which is bit-identical rather than equal."""
    for basis in (None, "density"):
        m = compile_tof_model(silicon(), bank(), blank(basis))
        assert m.channel_width_factor() is None
        assert m.intensity_basis == basis
    assert compile_tof_model(silicon(), bank(),
                             blank("counts")).intensity_basis == "counts"


def test_the_width_is_measured_before_the_fit_window_is_cut():
    """A width is a property of the histogram's channel layout, so it is taken
    on the whole abscissa and then masked.  Measuring it on the cut grid would
    report the window's own edge — or an excluded region's gap — as a channel
    width, which is the one place this could be wrong by a factor rather than
    by a rounding."""
    x, true_w = log_grid()
    lo, hi = 12000.0, 30000.0
    m = compile_tof_model(silicon(), bank(), blank("counts"),
                          tof_limits=(lo, hi))
    keep = (x >= lo) & (x <= hi)
    assert m.channel_width_factor() == pytest.approx(true_w[keep], rel=2e-6)

    gapped = blank("counts").model_copy(
        update={"excluded_regions": [(20000.0, 21000.0)]})
    m2 = compile_tof_model(silicon(), bank(), gapped)
    kept = keep & ~((x >= 20000.0) & (x <= 21000.0))
    m2b = compile_tof_model(silicon(), bank(), gapped, tof_limits=(lo, hi))
    assert m2b.channel_width_factor() == pytest.approx(true_w[kept], rel=2e-6)
    assert len(m2.channel_width_factor()) < len(x)


def test_the_width_multiplies_the_bragg_sum_exactly_once_and_not_the_background():
    """The trap this rung names: **never multiply by W twice.**

    Two independent statements.  One, the calculated Bragg component with the
    factor on is the component with it off times W, to the bit — so the factor
    is applied exactly once and not squared.  Two, ``evaluate`` is that
    product **plus an unmultiplied background**: the background is fitted in
    the observed space, so whatever W does to it is already in the
    coefficients it refines, and applying the shape there as well would apply
    it twice to the one curve that never needed it once.
    """
    st, ins = silicon(), bank()
    ins.background.coefficients[0].value = 200.0
    v = values_of(st, ins)
    off = compile_tof_model(st, ins, blank("density"))
    on = compile_tof_model(st, ins, blank("counts"))
    w = on.channel_width_factor()

    bragg_off = np.asarray(off.bragg_component(v))
    bragg_on = np.asarray(on.bragg_component(v))
    assert np.array_equal(bragg_on, bragg_off * w)

    bkg = np.asarray(on.background(v))
    assert np.array_equal(np.asarray(off.background(v)), bkg)
    assert np.array_equal(np.asarray(on.evaluate(v)), bragg_off * w + bkg)


def test_an_unstated_basis_is_bit_identical_to_a_declared_density():
    """The compatibility claim, asserted rather than argued: ``None`` is the
    behaviour every flight-time fit had before this field existed."""
    st, ins = silicon(), bank()
    v = values_of(st, ins)
    a = np.asarray(compile_tof_model(st, ins, blank(None)).evaluate(v))
    b = np.asarray(compile_tof_model(st, ins, blank("density")).evaluate(v))
    assert np.array_equal(a, b)


def test_the_constant_wavelength_arm_does_not_read_the_field():
    """A ``"counts"`` pattern with a constant-wavelength instrument is not
    affected — the assert, not the assurance.  ``CompiledModel`` carries no
    such attribute at all, and the two curves are byte-identical."""
    st = silicon()
    ins = rx.Instrument.bragg_brentano(radiation="CuKa1")
    tt = np.arange(20.0, 90.0, 0.02)
    kw = dict(two_theta=tt.tolist(), intensity=[1.0] * len(tt))
    v = values_of(st, ins)
    plain = compile_model(st, ins, PatternData(**kw))
    counted = compile_model(st, ins, PatternData(**kw, intensity_basis="counts"))
    assert not hasattr(plain, "channel_width")
    assert np.array_equal(np.asarray(plain.evaluate(v)),
                          np.asarray(counted.evaluate(v)))


# ------------------------------------------- the positive arm and its control
def _generated(structure, instrument, basis, seed: int) -> PatternData:
    """A pattern generated from the compiled model, with Poisson noise.

    ``basis`` is the basis the *generating* model declares, so a ``"counts"``
    pattern really does carry the width factor in its own numbers rather than
    being asserted to.
    """
    x, _ = log_grid()
    structure.phases[0].scale.value = 2.0e4 if basis != "counts" else 2.0e3
    instrument.background.coefficients[0].value = 200.0
    model = compile_tof_model(structure, instrument, blank(basis))
    table = ParameterTable(structure, instrument)
    y = np.asarray(model.evaluate(table.decode(table.x0())), dtype=np.float64)
    rng = np.random.default_rng(seed)
    return PatternData(tof=x.tolist(), intensity_basis=basis,
                       intensity=rng.poisson(np.maximum(y, 0.0)).astype(
                           np.float64).tolist())


def _refit(structure, instrument, data):
    ref = rx.Refinement(structure, instrument, history=False)
    plan = rx.RefinementPlan(stages=[
        rx.Stage("scale_bkg", ["phases.*.scale", "instrument.background.c*"]),
        rx.Stage("late", ["phases.*.cell.a", "phases.*.atoms.*.biso"]),
    ])
    plan.intermediate_ftol = None
    return ref.fit(data, plan=plan)


def test_leaving_out_the_channel_width_biases_biso_and_costs_rwp():
    """The negative control the factor has to earn its place against.

    A pattern is **generated** in counts on a log-stepped bank — W runs a
    factor of 5.6 across it, which is a slope in flight time and not a scale —
    then refined twice: once declaring the basis it was generated in, once
    declaring a density, which is the model this arm had before this commit.

    Biso moves **up** when the factor is left out, and it must: W rises with
    T, i.e. with d on a fixed-angle bank, so a model without it under-predicts
    the long-d end, and the only smooth thing that lifts the long-d end
    relative to the short one is a *larger* displacement parameter.  That is
    the same direction, and the same mechanism, as the real banks in the
    rung's report.
    """
    generated_biso = 0.5
    data = _generated(silicon(generated_biso), bank(), "counts", seed=20260906)
    w = compile_tof_model(silicon(), bank(), blank("counts")
                          ).channel_width_factor()
    assert w[-1] / w[0] > 5.0     # the arm is a control only if W really moves

    right = _refit(silicon(1.0), bank(), data)
    wrong = _refit(silicon(1.0), bank(),
                   data.model_copy(update={"intensity_basis": "density"}))
    b_right = {p.path: p for p in right.parameters}["phases.0.atoms.0.biso"]
    b_wrong = {p.path: p for p in wrong.parameters}["phases.0.atoms.0.biso"]

    assert abs(b_right.value - generated_biso) < 3.0 * b_right.stderr
    assert b_wrong.value > generated_biso + 0.1
    assert wrong.statistics.rwp > 1.2 * right.statistics.rwp


def test_declaring_counts_on_a_density_pattern_is_the_same_error_reversed():
    """The positive arm's mirror, so the control cannot pass by always being
    biased one way: a density fitted **as** counts multiplies by W once too
    often and Biso moves the other way."""
    generated_biso = 0.5
    data = _generated(silicon(generated_biso), bank(), "density", seed=20260907)
    right = _refit(silicon(1.0), bank(), data)
    twice = _refit(silicon(1.0), bank(),
                   data.model_copy(update={"intensity_basis": "counts"}))
    b_right = {p.path: p for p in right.parameters}["phases.0.atoms.0.biso"]
    b_twice = {p.path: p for p in twice.parameters}["phases.0.atoms.0.biso"]
    assert abs(b_right.value - generated_biso) < 3.0 * b_right.stderr
    assert b_twice.value < generated_biso - 0.1
    assert twice.statistics.rwp > 1.2 * right.statistics.rwp


# ------------------------------------------------------------- what it reports
def test_the_three_states_report_three_different_things():
    """A factor applied and not reported is the worst of the states, and an
    *unestablished* one that a user cannot see is the second worst."""
    data = _generated(silicon(0.5), bank(), "counts", seed=20260906)

    on = _refit(silicon(0.5), bank(), data)
    said = next(d for d in on.diagnostics if d.code == "TOF_CHANNEL_WIDTH_APPLIED")
    assert said.level == "info" and "counts" in said.message
    assert "µs" in said.message          # W at both ends of the window
    assert "TOF_INTENSITY_BASIS_ASSUMED" not in [d.code for d in on.diagnostics]

    declared = _refit(silicon(0.5), bank(),
                      data.model_copy(update={"intensity_basis": "density"}))
    codes = [d.code for d in declared.diagnostics]
    assert "TOF_CHANNEL_WIDTH_APPLIED" not in codes
    assert "TOF_INTENSITY_BASIS_ASSUMED" not in codes

    unstated = _refit(silicon(0.5), bank(),
                      data.model_copy(update={"intensity_basis": None}))
    warned = next(d for d in unstated.diagnostics
                  if d.code == "TOF_INTENSITY_BASIS_ASSUMED")
    assert warned.level == "warning" and warned.where == ["intensity_basis"]
    assert "'density'" in warned.message and "intensity_basis" in warned.suggestion


def test_the_constant_wavelength_arm_reports_nothing_about_it():
    """The field is silent on the arm that ignores it, whatever it says."""
    st = silicon()
    ins = rx.Instrument.bragg_brentano(radiation="CuKa1")
    tt = np.arange(20.0, 90.0, 0.05)
    v = values_of(st, ins)
    model = compile_model(st, ins, PatternData(
        two_theta=tt.tolist(), intensity=[1.0] * len(tt)))
    y = np.asarray(model.evaluate(v)) + 50.0
    data = PatternData(two_theta=tt.tolist(), intensity=y.tolist(),
                       intensity_basis="counts")
    res = _refit(silicon(1.0), rx.Instrument.bragg_brentano(radiation="CuKa1"), data)
    codes = [d.code for d in res.diagnostics]
    assert "TOF_CHANNEL_WIDTH_APPLIED" not in codes
    assert "TOF_INTENSITY_BASIS_ASSUMED" not in codes
