"""R_Bragg and R_F: the observed-intensity partition and eqs (13)/(14).

McCusker et al. (1999) §11 defines both against an I(obs) that is the observed
pattern *partitioned according to the structural model*.  That makes the whole
computation checkable against closed forms rather than against a remembered
number, which is what this file does:

* a **noiseless pattern generated by the model itself** must partition back to
  I(obs) = I(calc) to fp precision, so R_B = R_F = 0.  The partition is a fixed
  point of its own model — the one statement that pins the arithmetic end to
  end, windows and emission lines included;
* a pattern generated at scale S and read against a model at **1.2·S** must give
  R_B = 0.2 and R_F = √1.2 − 1 exactly, because every reflection's obs/calc
  ratio is then 1/1.2 and the sums collapse.  A wrong emission-line aggregation
  lands somewhere else, which is what makes the Kα-doublet form of this test the
  double-counting pin;
* the mode semantics, which are about what is *absent*, not what is computed.
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from rietx import Instrument, PatternData, Refinement
from rietx.model.forward import compile_model
from rietx.optimize.statistics import structure_r_factors
from rietx.params.vector import ParameterTable
from rietx.schemas.common import Parameter
from rietx.schemas.instrument import BackgroundChebyshev
from rietx.schemas.structure import MARCH_R_MIN, PreferredOrientation
from tests.test_refine_synthetic import (
    TRUE_A,
    TRUE_BKG,
    TRUE_SCALE,
    TRUE_W,
    TRUE_ZERO,
    WAVELENGTH,
    perturbed_models,
    synthesize,
)
from tests.test_schemas import make_lab6

OUT = Path(__file__).parent / "output"


def _save(result, name: str) -> None:
    """Write an obs/calc/diff PNG (skipped if matplotlib is unavailable)."""
    pytest.importorskip("matplotlib")
    OUT.mkdir(exist_ok=True)
    from rietx.viz.plots import plot_result

    plot_result(result, path=str(OUT / name))


def _lab6_at(a: float = TRUE_A, *, scale: float = TRUE_SCALE,
             wavelength: float = WAVELENGTH, doublet: bool = False,
             march_r: float | None = None):
    """LaB6 + a Debye-Scherrer instrument at known truth."""
    s = make_lab6()
    for c in ("a", "b", "c"):
        getattr(s.phases[0].cell, c).value = a
    s.phases[0].scale.value = scale
    if march_r is not None:
        s.phases[0].preferred_orientation = PreferredOrientation(
            axis=(1, 0, 0), r=Parameter(value=march_r, min=MARCH_R_MIN))
    ins = (Instrument.bragg_brentano(radiation="CuKa") if doublet
           else Instrument.debye_scherrer(wavelength=wavelength))
    ins.zero_shift.value = TRUE_ZERO
    ins.profile.w.value = TRUE_W if not doublet else 0.005
    ins.background = BackgroundChebyshev(
        coefficients=[Parameter(value=v) for v in TRUE_BKG])
    return s, ins


def _noiseless(structure, instrument, tt: np.ndarray) -> PatternData:
    """The model's own pattern, evaluated exactly — no noise, no rounding."""
    blank = PatternData(two_theta=tt.tolist(),
                        intensity=np.zeros_like(tt).tolist())
    model = compile_model(structure, instrument, blank, mode="rietveld")
    table = ParameterTable(structure, instrument)
    y = model.evaluate(table.decode(table.x0()))
    return PatternData(two_theta=model.tt.tolist(), intensity=y.tolist())


def _partition_r(structure, instrument, pattern):
    """(R_B, R_F, n, I_obs, I_calc) for phase 0 at the models' stored values."""
    model = compile_model(structure, instrument, pattern, mode="rietveld")
    table = ParameterTable(structure, instrument)
    values = table.decode(table.x0())
    i_obs, i_calc = model.structure_intensity_partition(values)[0]
    r_b, r_f, n = structure_r_factors(
        i_obs, i_calc, model.phases[0].reflections.multiplicity)
    return r_b, r_f, n, i_obs, i_calc


# ---------------------------------------------------------------- fixed point
@pytest.mark.parametrize("march_r", [None, 0.7])
def test_partition_of_its_own_pattern_is_the_identity(march_r):
    """I(obs) = I(calc) to fp precision when the data *is* the model.

    The strongest available pin, because it constrains every factor at once:
    the profile masses, the frozen windows, the shared y_bragg denominator and
    the multiplicity all have to be handled consistently or the ratio drifts
    off 1.  Nothing here is a reference value to be updated.

    Run with preferred orientation on as well, because March-Dollase is the one
    correction folded into the intensity *before* the others (``phase_peaks``
    multiplies P into ``base``) and it is strongly hkl-dependent: a P that
    reached the observed share but not the calculated one would show as a
    per-reflection ratio, not a uniform offset, so only the r ≠ 1 row sees it.
    """
    s, ins = _lab6_at(march_r=march_r)
    tt = np.arange(3.0, 24.0, 0.005)
    r_b, r_f, n, i_obs, i_calc = _partition_r(s, ins, _noiseless(s, ins, tt))

    assert n == 19
    assert r_b == pytest.approx(0.0, abs=1e-12)
    assert r_f == pytest.approx(0.0, abs=1e-12)
    assert np.allclose(i_obs, i_calc, rtol=1e-12)


def test_uniform_scale_error_gives_the_closed_form_r_values():
    """Read a pattern of scale S against a model at 1.2·S.

    Every reflection's obs/calc ratio is then exactly 1/1.2, so both sums
    collapse to that ratio's distance from 1, normalised by the ratio:
    eq (14) gives (1 − 1/1.2)·1.2 = 0.2 and eq (13), on amplitudes, gives
    (1 − 1/√1.2)·√1.2 = √1.2 − 1.
    Two independent things are pinned: that the correction factors really do
    divide out (a leftover Lp or absorption factor would make the ratio
    angle-dependent and neither sum would close), and that R_F is the root of
    R_B's quantity rather than a second copy of it.
    """
    s_true, ins_true = _lab6_at()
    tt = np.arange(3.0, 24.0, 0.005)
    pattern = _noiseless(s_true, ins_true, tt)

    s_off, ins_off = _lab6_at(scale=TRUE_SCALE * 1.2)
    r_b, r_f, _, _, _ = _partition_r(s_off, ins_off, pattern)

    assert r_b == pytest.approx(0.2, rel=1e-9)
    assert r_f == pytest.approx(math.sqrt(1.2) - 1.0, rel=1e-9)


def test_i_calc_is_multiplicity_times_f_squared_and_nothing_else():
    """Eq (14) defines I_hkl = m·F², so no correction may survive in I(calc).

    Checked against the reflection table's own |F|², which is computed by a
    different call on a different path — the scale, the line weight, Lp,
    extinction, absorption, roughness and preferred orientation are all in
    ``ReflectionRow.intensity`` and none of them may be in I(calc).  The
    closed-form tests above cannot see a *uniform* leak (it cancels in the
    ratio), so this is the one that pins the units.
    """
    from rietx.io.exporters import reflection_table

    s, ins = _lab6_at()
    tt = np.arange(3.0, 24.0, 0.005)
    pattern = _noiseless(s, ins, tt)
    model = compile_model(s, ins, pattern, mode="rietveld")
    table = ParameterTable(s, ins)
    values = table.decode(table.x0())

    _, i_calc = model.structure_intensity_partition(values)[0]
    rows = [r for r in reflection_table(model, values, s) if r.line == 0]
    assert len(rows) == len(i_calc)
    expected = np.array([r.multiplicity * r.f_squared for r in rows])
    assert np.allclose(i_calc, expected, rtol=1e-12)
    # and the scale really is out: I(calc) must not move with it
    s2, ins2 = _lab6_at(scale=TRUE_SCALE * 3.0)
    m2 = compile_model(s2, ins2, pattern, mode="rietveld")
    t2 = ParameterTable(s2, ins2)
    _, i_calc2 = m2.structure_intensity_partition(t2.decode(t2.x0()))[0]
    assert np.allclose(i_calc2, i_calc, rtol=1e-12)


def test_emission_doublet_is_one_reflection_not_two():
    """A Cu Kα1/Kα2 pair must not count its reflection twice.

    The sums of eqs (13)/(14) run over hkl; the partition runs over
    (line, reflection).  Aggregating the lines into the orbit before summing is
    what keeps the two consistent, and the closed form above is the test that
    can tell: partitioning the doublet's counts but normalising by one line's
    profile mass lands at ratio (w₁+w₂)/w₁ ≈ 1.5 rather than 1, so the fixed
    point moves off zero and the scale-error form moves off 0.2.  Reflection
    *counts* are asserted too — a per-line list would be twice as long.
    """
    s_true, ins_true = _lab6_at(doublet=True)
    assert len(ins_true.source.lines) == 2, "this test needs a real doublet"
    tt = np.arange(18.0, 100.0, 0.02)
    pattern = _noiseless(s_true, ins_true, tt)

    model = compile_model(s_true, ins_true, pattern, mode="rietveld")
    n_hkl = len(model.phases[0].reflections)

    r_b, r_f, n, i_obs, _ = _partition_r(s_true, ins_true, pattern)
    assert len(i_obs) == n_hkl and n == n_hkl
    assert r_b == pytest.approx(0.0, abs=1e-12)
    assert r_f == pytest.approx(0.0, abs=1e-12)

    s_off, ins_off = _lab6_at(scale=TRUE_SCALE * 1.2, doublet=True)
    r_b_off, r_f_off, _, _, _ = _partition_r(s_off, ins_off, pattern)
    assert r_b_off == pytest.approx(0.2, rel=1e-9)
    assert r_f_off == pytest.approx(math.sqrt(1.2) - 1.0, rel=1e-9)


def test_a_reflection_off_the_ewald_sphere_is_dropped_not_zeroed():
    """No partition ⇒ NaN in both arrays, and out of the sums.

    Zero would enter eq (14) as perfect agreement on a reflection nothing was
    measured for.  ``n_reflections`` is the field that says so.
    """
    io = np.array([100.0, np.nan, 25.0])
    ic = np.array([100.0, np.nan, 50.0])
    mult = np.array([6.0, 12.0, 8.0])
    r_b, r_f, n = structure_r_factors(io, ic, mult)

    assert n == 2
    # eq (14) over the two survivors: (|100−100| + |25−50|) / (100 + 25)
    assert r_b == pytest.approx(25.0 / 125.0)
    # eq (13) on |F| = √(I/m), same two
    f_obs = [math.sqrt(100.0 / 6.0), math.sqrt(25.0 / 8.0)]
    f_calc = [math.sqrt(100.0 / 6.0), math.sqrt(50.0 / 8.0)]
    assert r_f == pytest.approx(
        sum(abs(a - b) for a, b in zip(f_obs, f_calc, strict=True))
        / sum(f_obs))


def test_no_partitionable_reflection_is_none_not_zero():
    """A phase with nothing to compare reports None — not a perfect fit."""
    nan3 = np.full(3, np.nan)
    assert structure_r_factors(nan3, nan3, np.ones(3)) == (None, None, 0)
    zeros = np.zeros(3)
    r_b, r_f, n = structure_r_factors(zeros, zeros, np.ones(3))
    assert n == 3 and r_b is None and r_f is None


# -------------------------------------------------------------- on a real fit
def test_a_converged_fit_reports_both_indices_per_phase():
    pattern = synthesize()
    structure, ins = perturbed_models()
    ref = Refinement(structure, ins, history=False)
    result = ref.fit(pattern, plan="mccusker_default")

    assert result.status == "converged"
    assert len(result.phase_agreement) == 1
    row = result.phase_agreement[0]
    assert row.name == "LaB6"
    assert row.n_reflections > 0
    # a good structural model on its own data: both well under Rwp's own scale,
    # and R_F below R_B because amplitudes halve a relative intensity error
    assert 0.0 < row.r_bragg < 0.10
    assert 0.0 < row.r_f < row.r_bragg
    _save(result, "structure_r_lab6.png")


# ------------------------------------------------------------ mode semantics
@pytest.mark.parametrize("mode", ["lebail", "pawley"])
def test_absent_for_cause_outside_rietveld(mode):
    """In both structure-free modes the partition would be circular.

    Le Bail's intensities *are* the partition and Pawley's are refined θ, so
    I(obs) would be compared against itself.  The row is absent, and the
    method that would produce it refuses rather than returning the number.
    """
    pattern = synthesize()
    structure, ins = perturbed_models()
    result = Refinement(structure, ins, history=False).fit(pattern, mode=mode)

    assert result.phase_agreement == []

    model = compile_model(structure, ins, pattern, mode=mode)
    values = ParameterTable(structure, ins).decode(ParameterTable(
        structure, ins).x0())
    with pytest.raises(RuntimeError, match="structure factors"):
        model.structure_intensity_partition(values)


def test_the_partition_writes_nothing():
    """Evaluate-only: no buffer, no θ, no recompile.

    The frozen-per-stage invariant is why this matters — a partition that
    committed to ``hkl_intensity`` would change what a later stage computed.
    """
    s, ins = _lab6_at()
    tt = np.arange(3.0, 24.0, 0.005)
    pattern = _noiseless(s, ins, tt)
    model = compile_model(s, ins, pattern, mode="rietveld")
    table = ParameterTable(s, ins)
    theta = table.x0()
    values = table.decode(theta)

    before = model.evaluate(values).copy()
    buffers = [None if cp.hkl_intensity is None else cp.hkl_intensity.copy()
               for cp in model.phases]

    model.structure_intensity_partition(values)
    model.structure_intensity_partition(values)  # idempotent, twice over

    assert np.array_equal(model.evaluate(values), before)
    for cp, buf in zip(model.phases, buffers, strict=True):
        assert (cp.hkl_intensity is None) == (buf is None)
        if buf is not None:
            assert np.array_equal(cp.hkl_intensity, buf)


# ---------------------------------------------------------------- CIF export
def test_cif_carries_the_tags_and_the_esd_method():
    """The dictionary tags, on the phase's own block, plus the §10 sentence."""
    pattern = synthesize()
    structure, ins = perturbed_models()
    ref = Refinement(structure, ins, history=False)
    result = ref.fit(pattern, plan="mccusker_default")

    from rietx.io.exporters import refinement_cif_doc

    doc = refinement_cif_doc(result, ref.fitted_structure,
                             ref.fitted_instrument)
    block = doc.sole_block()
    row = result.phase_agreement[0]

    assert float(block.find_value("_refine_ls_R_I_factor")) == pytest.approx(
        row.r_bragg, rel=1e-6)
    assert float(block.find_value("_refine_ls_R_factor_all")) == pytest.approx(
        row.r_f, rel=1e-6)
    assert int(block.find_value("_refine_ls_number_reflns")) == row.n_reflections

    # gap 8: the method, not just the factor.  The base estimator has to be
    # named — an inflation factor alone does not say what it multiplied.
    details = block.find_value("_pd_proc_ls_special_details")
    assert "(J^T J)^-1" in details
    assert "chi^2_red" in details
    assert "Berar-Lelann" in details

    # ...and a result carrying no esds must not describe how they were made.
    # An evaluate-only or replayed result has none, and a method statement
    # about nothing is a claim, not a disclosure.
    bare = result.model_copy(deep=True)
    for p in bare.parameters:
        p.stderr = None
    bare_block = refinement_cif_doc(bare, ref.fitted_structure,
                                    ref.fitted_instrument).sole_block()
    assert bare_block.find_value("_pd_proc_ls_special_details") is None
    # the profile R factors are unconditional and must still be there
    assert bare_block.find_value("_pd_proc_ls_prof_wR_factor") is not None
