"""WP-1203 — the help keys the frontend is held to.

The GUI's popover addresses the corpus by ``arm:name`` keys written into the
markup (``<Help for="stage_fields:max_iter">``).  A key that names nothing
renders "not yet described" under a real control and nothing fails, which is
the drift this fixture exists to catch: the same shape as
``test_gui_fnmatch.py``'s glob corpus, and for the same reason — python owns
the vocabulary, TypeScript proves it can state it, and vitest has to run
without pytest having run first.

The fixture carries the **names only**, never the prose.  ``rietx.help`` is the
one authority for what a name means (root CLAUDE.md), and a committed copy of
its 59 kB of descriptions would be a second one: it would churn on every
wording edit and could disagree with the module while every test stayed green.
What a client needs pinned is the key set, which is 3 kB and cannot drift
silently.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from rietx import _about
from rietx.help import help_registry

FIXTURE = Path(__file__).parent / "data" / "gui" / "help_keys.json"

#: The arms, in the order ``gui/src/lib/help.ts`` declares them.  Named here so
#: an arm added to the registry with no place in the client's ``ARMS`` fails
#: rather than arriving as an unaddressable key.
ARMS = (
    "parameters",
    "stage_fields",
    "plans",
    "peak_flags",
    "peak_diagnostics",
    "peak_origins",
    "reader_options",
    "instrument_fields",
    "search_fields",
)


def _keys() -> list[str]:
    """Every ``arm:name`` the corpus can be addressed by, sorted.

    The parameters arm contributes one key per *glob* rather than per entry,
    because a glob is what ``ParameterRow.help_key`` carries and therefore what
    a client resolves.
    """
    registry = help_registry()
    out: list[str] = []
    for entry in registry["parameters"]:
        out += [f"parameters:{glob}" for glob in entry["paths"]]
    for arm in ARMS:
        if arm == "parameters":
            continue
        out += [f"{arm}:{name}" for name in registry[arm]]
    return sorted(out)


def _corpus() -> dict:
    return {
        "_comment": (
            "Generated by tests/test_gui_help.py from rietx.help.help_registry(); "
            "consumed by gui/src/lib/help.test.ts. Do not hand-edit — run "
            "`.venv/bin/python -m pytest tests/test_gui_help.py` to regenerate. "
            "Names only: the prose lives in src/rietx/help.py and a copy of it "
            "here would be a second authority on it."),
        "docs_url": _about.DOCS_URL,
        "arms": list(ARMS),
        "keys": _keys(),
    }


def _dump(corpus: dict) -> str:
    return json.dumps(corpus, indent=1) + "\n"


def test_the_committed_help_key_fixture_is_current():
    """Regenerate and compare — the dist-digest rule, one artefact over."""
    text = _dump(_corpus())
    if not FIXTURE.is_file() or FIXTURE.read_text(encoding="utf-8") != text:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(text, encoding="utf-8")
        raise AssertionError(
            f"{FIXTURE.relative_to(Path(__file__).parent.parent)} was stale and "
            "has been rewritten; commit it (the vitest reads the committed copy, "
            "and node never runs this suite)")


def test_the_arms_named_here_are_the_registry_s_own():
    """An arm the client cannot address is an arm whose entries are unreachable."""
    assert set(ARMS) == set(help_registry()), (
        f"missing: {sorted(set(help_registry()) - set(ARMS))}; "
        f"naming nothing: {sorted(set(ARMS) - set(help_registry()))} — add it "
        "to ARMS here and to gui/src/lib/help.ts")


def test_every_key_names_an_arm_and_a_name():
    """`arm:name`, with the arm first — a bare name would resolve by order.

    Several vocabularies overlap: ``seed`` is a stage field *and* a search
    control, ``preset`` a search control *and* a word a plan owns.  Resolving a
    bare key would make its answer a property of declaration order, which is
    the failure ``help_key_for``'s exactly-one-family test rules out one rank
    down.
    """
    keys = json.loads(FIXTURE.read_text(encoding="utf-8"))["keys"]
    assert len(keys) > 100
    for key in keys:
        arm, _, name = key.partition(":")
        assert arm in ARMS, key
        assert name, key
    assert len(set(keys)) == len(keys), "a key appears twice"


def test_the_overlap_this_key_shape_exists_for_is_real():
    """Not a hypothetical: assert the colliding bare names actually collide.

    A rule justified by a collision that has since been renamed away is a rule
    nobody can check, so this fails if the overlap disappears and the
    justification above needs rewriting.
    """
    registry = help_registry()
    bare = [name for arm in ARMS if arm != "parameters" for name in registry[arm]]
    repeated = sorted({n for n in bare if bare.count(n) > 1})
    assert repeated, (
        "no bare name is claimed by two arms any more — the `arm:name` key "
        "shape is still right, but help.ts's docstring cites a collision that "
        "no longer exists")


def test_the_client_declares_the_same_arms():
    """`lib/help.ts`'s ARMS is the other half of the bijection."""
    source = (Path(__file__).parent.parent / "gui" / "src" / "lib"
              / "help.ts").read_text(encoding="utf-8")
    block = re.search(r"export const ARMS = \[(.*?)\] as const", source, re.S)
    assert block, "ARMS moved in gui/src/lib/help.ts"
    declared = re.findall(r'"([a-z_]+)"', block.group(1))
    assert declared == list(ARMS), (
        f"gui/src/lib/help.ts declares {declared}, this module {list(ARMS)}")
